services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    # environment:
      # DOMAIN: "https://vaultwarden.treikeh.com"
    volumes:
      - "~/docker/vaultwarden:/data"
    ports:
      - "8001:80"
